export const ADD_BRAND_REQUEST = "ADD_BRAND_REQUEST"
export const ADD_BRAND_SUCCESS = "ADD_BRAND_SUCCESS"
export const ADD_BRAND_FAIL = "ADD_BRAND_FAIL"

export const LIST_BRAND_REQUEST = "LIST_BRAND_REQUEST"
export const LIST_BRAND_SUCCESS = "LIST_BRAND_SUCCESS"
export const LIST_BRAND_FAIL = "LIST_BRAND_FAIL"