export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST"
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS"
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL"

export const SUBCATEGORY_LIST_REQUEST = "SUBCATEGORY_LIST_REQUEST"
export const SUBCATEGORY_LIST_SUCCESS = "SUBCATEGORY_LIST_SUCCESS"
export const SUBCATEGORY_LIST_FAIL = "SUBCATEGORY_LIST_FAIL"

export const LISTSUBCATEGORY_LIST_REQUEST = "LISTSUBCATEGORY_LIST_REQUEST"
export const LISTSUBCATEGORY_LIST_SUCCESS = "LISTSUBCATEGORY_LIST_SUCCESS"
export const LISTSUBCATEGORY_LIST_FAIL = "LISTSUBCATEGORY_LIST_FAIL"


