export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAILS = 'PRODUCT_LIST_FAILS'

export const PRODUCTBYID_REQUEST = 'PRODUCTBYID_REQUEST'
export const PRODUCTBYID_SUCCESS = 'PRODUCTBYID_SUCCESS'
export const PRODUCTBYID_FAILS = 'PRODUCTBYID_FAILS'