export const ADD_SELLER_REQUEST = "ADD_SELLER_REQUEST"
export const ADD_SELLER_SUCCESS = "ADD_SELLER_SUCCESS"
export const ADD_SELLER_FAIL = "ADD_SELLER_FAIL"

export const LIST_SELER_REQUEST = "LIST_SELER_REQUEST"
export const LIST_SELER_SUCCESS = "LIST_SELER_SUCCESS"
export const LIST_SELER_FAIL = "LIST_SELER_FAIL"