export const ADD_SIZE_REQUEST = "ADD_SIZE_REQUEST"
export const ADD_SIZE_SUCCESS = "ADD_SIZE_SUCCESS"
export const ADD_SIZE_FAIL = "ADD_SIZE_FAIL"


export const LIST_SIZE_REQUEST = "LIST_SIZE_REQUEST"
export const LIST_SIZE_SUCCESS = "LIST_SIZE_SUCCESS"
export const LIST_SIZE_FAIL = "LIST_SIZE_FAIL"