export const ADD_SIGNUP_REQUEST = 'ADD_SIGNUP_REQUEST'
export const ADD_SIGNUP_SUCCESS = 'ADD_SIGNUP_SUCCESS'
export const ADD_SIGNUP_FAIL = 'ADD_SIGNUP_FAIL'


export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const AUTH_CHECK_REQUEST = 'AUTH_CHECK_REQUEST'
export const AUTH_CHECK_SUCCESS = 'AUTH_CHECK_SUCCESS'
export const AUTH_CHECK_FAIL = 'AUTH_CHECK_FAIL'
