export const ADD_BRAND_REQUEST = "ADD_BRAND_REQUEST"
export const ADD_BRAND_SUCCESS = "ADD_BRAND_SUCCESS"
export const ADD_BRAND_FAIL = "ADD_BRAND_FAIL"

export const LIST_BRAND_REQUEST = "LIST_BRAND_REQUEST"
export const LIST_BRAND_SUCCESS = "LIST_BRAND_SUCCESS"
export const LIST_BRAND_FAIL = "LIST_BRAND_FAIL"

export const ACTIVE_BRAND_REQUEST = "ACTIVE_BRAND_REQUEST"
export const ACTIVE_BRAND_SUCCESS = "ACTIVE_BRAND_SUCCESS"
export const ACTIVE_BRAND_FAIL = "ACTIVE_BRAND_FAIL"

export const DELETE_BRAND_REQUEST = "DELETE_BRAND_REQUEST"
export const DELETE_BRAND_SUCCESS = "DELETE_BRAND_SUCCESS"
export const DELETE_BRAND_FAIL = "DELETE_BRAND_FAIL"