export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST"
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS"
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL"

export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST"
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS"
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL"

export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST"
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS"
export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL"

export const ACTIVE_CATEGORY_REQUEST = "ACTIVE_CATEGORY_REQUEST"
export const ACTIVE_CATEGORY_SUCCESS = "ACTIVE_CATEGORY_SUCCESS"
export const ACTIVE_CATEGORY_FAIL = "ACTIVE_CATEGORY_FAIL"

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST"
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS"
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL"

export const EDIT_CATEGORY_REQUEST = "EDIT_CATEGORY_REQUEST"
export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS"
export const EDIT_CATEGORY_FAIL = "EDIT_CATEGORY_FAIL"