export const ADD_COLOR_REQUEST = "ADD_COLOR_REQUEST"
export const ADD_COLOR_SUCCESS = "ADD_COLOR_SUCCESS"
export const ADD_COLOR_FAIL = "ADD_COLOR_FAIL"


export const LIST_COLOR_REQUEST = "LIST_COLOR_REQUEST"
export const LIST_COLOR_SUCCESS = "LIST_COLOR_SUCCESS"
export const LIST_COLOR_FAIL = "LIST_COLOR_FAIL"

export const ACTIVE_COLOR_REQUEST = "ACTIVE_COLOR_REQUEST"
export const ACTIVE_COLOR_SUCCESS = "ACTIVE_COLOR_SUCCESS"
export const ACTIVE_COLOR_FAIL = "ACTIVE_COLOR_FAIL"

export const DELETE_COLOR_REQUEST = "DELETE_COLOR_REQUEST"
export const DELETE_COLOR_SUCCESS = "DELETE_COLOR_SUCCESS"
export const DELETE_COLOR_FAIL = "DELETE_COLOR_FAIL"