export const ADD_COLOR_REQUEST = "ADD_COLOR_REQUEST"
export const ADD_COLOR_SUCCESS = "ADD_COLOR_SUCCESS"
export const ADD_COLOR_FAIL = "ADD_COLOR_FAIL"


export const LIST_COLOR_REQUEST = "LIST_COLOR_REQUEST"
export const LIST_COLOR_SUCCESS = "LIST_COLOR_SUCCESS"
export const LIST_COLOR_FAIL = "LIST_COLOR_FAIL"