export const ADD_LIST_SUBCATEGORY_REQUEST = "ADD_LIST_SUBCATEGORY_REQUEST"
export const ADD_LIST_SUBCATEGORY_SUCCESS = "ADD_LIST_SUBCATEGORY_SUCCESS"
export const ADD_LIST_SUBCATEGORY_FAIL = "ADD_LIST_SUBCATEGORY_FAIL"

export const LIST_SUBCATEGORY_REQUEST = "LIST_SUBCATEGORY_REQUEST"
export const LIST_SUBCATEGORY_SUCCESS = "LIST_SUBCATEGORY_SUCCESS"
export const LIST_SUBCATEGORY_FAIL = "LIST_SUBCATEGORY_FAIL"

export const LIST_SUBCATEGORYBYID_REQUEST = "LIST_SUBCATEGORYBYID_REQUEST"
export const LIST_SUBCATEGORYBYID_SUCCESS = "LIST_SUBCATEGORYBYID_SUCCESS"
export const LIST_SUBCATEGORYBYID_FAIL = "LIST_SUBCATEGORYBYID_FAIL"