export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST"
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL"


export const MANAGE_PRODUCT_REQUEST = "MANAGE_PRODUCT_REQUEST"
export const MANAGE_PRODUCT_SUCCESS = "MANAGE_PRODUCT_SUCCESS"
export const MANAGE_PRODUCT_FAIL = "MANAGE_PRODUCT_FAIL"