export const ADD_SELLER_REQUEST = "ADD_SELLER_REQUEST"
export const ADD_SELLER_SUCCESS = "ADD_SELLER_SUCCESS"
export const ADD_SELLER_FAIL = "ADD_SELLER_FAIL"

export const LIST_SELER_REQUEST = "LIST_SELER_REQUEST"
export const LIST_SELER_SUCCESS = "LIST_SELER_SUCCESS"
export const LIST_SELER_FAIL = "LIST_SELER_FAIL"

export const ACTIVE_SELLER_REQUEST = "ACTIVE_SELLER_REQUEST"
export const ACTIVE_SELLER_SUCCESS = "ACTIVE_SELLER_SUCCESS"
export const ACTIVE_SELLER_FAIL = "ACTIVE_SELLER_FAIL"

export const DELETE_SELLER_REQUEST = "DELETE_SELLER_REQUEST"
export const DELETE_SELLER_SUCCESS = "DELETE_SELLER_SUCCESS"
export const DELETE_SELLER_FAIL = "DELETE_SELLER_FAIL"