export const ADD_SLIDER_REQUEST = "ADD_SLIDER_REQUEST"
export const ADD_SLIDER_SUCCESS = "ADD_SLIDER_SUCCESS"
export const ADD_SLIDER_FAIL = "ADD_SLIDER_FAIL"

export const LIST_SLIDER_REQUEST = "LIST_SLIDER_REQUEST"
export const LIST_SLIDER_SUCCESS = "LIST_SLIDER_SUCCESS"
export const LIST_SLIDER_FAIL = "LIST_SLIDER_FAIL"

export const ACTIVE_SLIDER_REQUEST = "ACTIVE_SLIDER_REQUEST"
export const ACTIVE_SLIDER_SUCCESS = "ACTIVE_SLIDER_SUCCESS"
export const ACTIVE_SLIDER_FAIL = "ACTIVE_SLIDER_FAIL"

export const DELETE_SLIDER_REQUEST = "DELETE_SLIDER_REQUEST"
export const DELETE_SLIDER_SUCCESS = "DELETE_SLIDER_SUCCESS"
export const DELETE_SLIDER_FAIL = "DELETE_SLIDER_FAIL"