export const ADD_SUBCATEGORY_REQUEST = "ADD_SUBCATEGORY_REQUEST"
export const ADD_SUBCATEGORY_SUCCESS = "ADD_SUBCATEGORY_SUCCESS"
export const ADD_SUBCATEGORY_FAIL = "ADD_SUBCATEGORY_FAIL"

export const SUBCATEGORY_LIST_REQUEST = "SUBCATEGORY_LIST_REQUEST"
export const SUBCATEGORY_LIST_SUCCESS = "SUBCATEGORY_LIST_SUCCESS"
export const SUBCATEGORY_LIST_FAIL = "SUBCATEGORY_LIST_FAIL"


export const SUBCATEGORYBYID_LIST_REQUEST = "SUBCATEGORYBYID_LIST_REQUEST"
export const SUBCATEGORYBYID_LIST_SUCCESS = "SUBCATEGORYBYID_LIST_SUCCESS"
export const SUBCATEGORYBYID_LIST_FAIL = "SUBCATEGORYBYID_LIST_FAIL"

export const DELETE_SUBCATEGORY_REQUEST = "DELETE_SUBCATEGORY_REQUEST"
export const DELETE_SUBCATEGORY_SUCCESS = "DELETE_SUBCATEGORY_SUCCESS"
export const DELETE_SUBCATEGORY_FAIL = "DELETE_SUBCATEGORY_FAIL"

